ERROR    tests_api.utils.logger:logger.py:39 REQUEST: method='GET' url='https://dev.agentum.pro/backend/api/users/achievement/registration' kwargs={'method': 'GET', 'url': 'https://dev.agentum.pro/backend/api/users/achievement/registration', 'params': None, 'headers': {'Authorization': 'Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz'}}
ERROR    tests_api.utils.logger:logger.py:40 ERROR: HTTPSConnectionPool(host='dev.agentum.pro', port=443): Max retries exceeded with url: /backend/api/users/achievement/registration (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb4ad195f30>, 'Connection to dev.agentum.pro timed out. (connect timeout=5000)'))